import type { Metadata } from 'next';
import type { FC, ReactElement, PropsWithChildren } from 'react';

import { GlobalProviders } from '@/providers';
import './globals.css';

export const metadata: Metadata = {
  title: 'ConTAnoS',
  description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({
  children,
}: PropsWithChildren): ReactElement => {
  return (
    <html lang="es" suppressHydrationWarning>
      <body>
        <GlobalProviders>{children}</GlobalProviders>
      </body>
    </html>
  );
};

export default RootLayout;
