using Api.Domain.Entities;

namespace Api.Domain.ViewModels.Server
{
    public class MessageVModel
    {
        public int SessionId { get; set; }
        public string UserName { get; set; } = string.Empty;
        public DateTime Date { get; set; }
        public string Text { get; set; } = string.Empty;
        public bool? IsModerated { get; set; }
        public bool? IsProfessional { get; set; }
        public bool? IsAutogenerated { get; set; } 
    }
}
